server {
    listen 80;
    listen [::]:80;
    server_name calendar.pangruitao.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 308 https://calendar.pangruitao.com$request_uri;
    }
}

